# Generated by Django 4.0.4 on 2022-05-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование статусов заявки')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Статусы заявки',
                'verbose_name_plural': 'Статусы заявки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shipping_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Публикация')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('Delivery_information', models.CharField(max_length=255, verbose_name='Информация для перевозчика')),
                ('Deliverier', models.CharField(max_length=255, verbose_name='Перевозчик')),
                ('Deliverier_phone', models.CharField(max_length=255, verbose_name='Телефон перевозчика')),
                ('shipper', models.CharField(max_length=255, verbose_name='Грузоотправитель')),
                ('shipper_inn', models.CharField(max_length=255, verbose_name='ИНН Грузоотправителя')),
                ('shipper_address', models.CharField(max_length=255, verbose_name='Адрес Грузоотправителя')),
                ('shipper_phone', models.CharField(max_length=255, verbose_name='Телефоны Грузоотправителя')),
                ('shipper_contacts', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('consignee', models.CharField(max_length=255, verbose_name='Грузополучатель')),
                ('consignee_address', models.CharField(max_length=255, verbose_name='Адрес Грузополучателя')),
                ('consignee_phone', models.CharField(max_length=255, verbose_name='Телефоны Грузополучателя')),
                ('Consignee_contacts', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('Consignee_workhours', models.CharField(max_length=255, verbose_name='Время работы склада Грузополучателя')),
                ('cargo_name', models.CharField(max_length=255, verbose_name='Наименование груза')),
                ('cargo_quantity', models.IntegerField(verbose_name='Фактическое количество мест')),
                ('cargo_addition', models.CharField(max_length=255, verbose_name='Дополнение к грузу')),
                ('cargo_addition_quantity', models.IntegerField(verbose_name='Доп. фактическое количество мест')),
                ('shipper_additional_services1', models.BooleanField(default=False, verbose_name='Дополнительная услуга перевозчика Жесткая упаковка по желанию клиента')),
                ('shipper_additional_services2', models.BooleanField(default=False, verbose_name='Дополнительная услуга перевозчика Доставка до двери в городе грузополучателя')),
                ('delivered_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ship.delivered_status', verbose_name='Статусы заказов')),
            ],
            options={
                'verbose_name': 'Заявки на отгрузку',
                'verbose_name_plural': 'Заявки на отгрузку',
                'ordering': ['id'],
            },
        ),
    ]
